.\" avenida.1
.\" Christian Koch <cfkoch@sdf.lonestar.org>
.Dd March 16, 2015
.Dt avenida 1
.Os
.Sh NAME
.Nm avenida
.Nd Avenida command line interpreter
.Sh SYNOPSIS
.Nm avenida
.Op Fl h
.Op Fl v
.Sh DESCRIPTION
The
.Nm
utility executes scripts written in Avnscript.
.Sh HISTORY
The
.Nm
tool was written by Christian Koch.
